# Background
image {
    monitor =
    path = /home/aseda/Pictures/wallpaper/pastel-dusk.png
    blur_size = 0
    blur_passes = 0
    zindex = 0
    size = 1080 # Pixel width of smaller side. Got from 'hyprctl monitors'
    rounding = 0
}

# Password Input
input-field {
    monitor =
    size = 250, 50
    position = 0, -20
    zindex = 10
    outer_color = rgba(191, 162, 240, 1.0)
    inner_color = rgba(30, 27, 43, 0.85)
    font_color = rgba(230, 225, 242, 1.0)
    check_color = rgba(240, 216, 154, 1.0)
    fail_color = rgba(240, 120, 142, 1.0)
    capslock_color = rgba(242, 167, 200, 1.0)
}

# Date Label
label {
    monitor =
    zindex=5
    text = cmd[update:1000] echo -e "$(LC_TIME=en_US.UTF-8 date +"%A, %B %d")"
    color = rgba(230, 225, 242, 0.90)
    font_size = 25
    font_family = SF Pro Display Semibold
    position = 0, 350
    halign = center
    valign = center
}

# Time Label
label {
    monitor =
    zindex = 5
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(230, 225, 242, 0.90)
    font_size = 120
    font_family = SF Pro Display Bold
    position = 0, 230
    halign = center
    valign = center
}
